#!/bin/sh
# pyominas setup script for Linux VM. Currently set to work with my installed
# directories, but the script could be rewritten to search for the necessary
# locations prior to adjusting environment varibles and launching python

APPLICATION=python
MODULES=pyominas_setup.py
export PYTHONSTARTUP=$MODULES

# ominas setup
. ~/.ominas/ominas_setup.sh

# environment variables
export LD_LIBRARY_PATH="/data/software/anaconda2/lib/:/usr/local/exelis/idl85/bin/bin.linux.x86_64"
export PYTHONPATH="/usr/local/exelis/idl85/bin/bin.linux.x86_64:/usr/local/exelis/idl85/lib/bridges"

# issues with Anaconda's activate script so I'm just adjusting PATH
# ideally, find activate and source it in this script
export PATH="/data/software/anaconda2/bin:$PATH"

# read arguments - better way of doing this?
# since I'm running pyton 2.7, I'm just going to use execfile for now
ARGS=""{
if [ $# ]; then 
	ARGS = "$1"
	echo ARGS
fi

# launch python
exec $APPLICATION

# attempting to return to shell
$SHELL
