#!/bin/sh
# pyominas setup script for Linux VM. Currently set to work with my installed
# directories, but the script could be rewritten to search for the necessary
# locations prior to adjusting environment varibles and launching python

APPLICATION=python
MODULES=pyominas_setup.py
export PYTHONSTARTUP=$MODULES

# ominas setup
. ~/.ominas/ominas_setup.sh

# environment variables
export LD_LIBRARY_PATH="/data/software/anaconda2/lib/:/usr/local/exelis/idl85/bin/bin.linux.x86_64"
export PYTHONPATH="/usr/local/exelis/idl85/bin/bin.linux.x86_64:/usr/local/exelis/idl85/lib/bridges"
export PATH="/data/software/anaconda2/bin:$PATH" # Ideally, find activate and source it.

# read arguments
ARG=
if $# ; then
	ARG=$1
	echo ARG
fi

# launch python
exec $APPLICATION "$@" $ARG

# attempting to return to shell
$SHELL
